import Config

# Configure your database
# Fast feedback while we're building things out. Production should keep the
# default 60s cron in config.exs.
config :mast, :check_interval_ms, 30_000

# In dev, stage SSH keys into priv/ssh/ (gitignored) so we don't ship
# the operator's whole ~/.ssh dir to Erlang's :ssh app. Symlink the
# real key file in as id_rsa / id_ed25519 etc.
config :mast, Mast.SSH.SSHKit, user_dir: Path.expand("../priv/ssh", __DIR__)

# Dev-only Cloak key. NOT a secret — committing it just means the dev DB is
# readable across machines. Production must override via MAST_VAULT_KEY in
# config/runtime.exs.
config :mast, Mast.Vault,
  ciphers: [
    default: {
      Cloak.Ciphers.AES.GCM,
      tag: "AES.GCM.V1", key: Base.decode64!("kPgTYjcl4fzpw6MQyILZmHe7AaZSPHl4Hbqu8jW9mUg=")
    }
  ]

config :mast, Mast.Repo,
  username: "mast",
  password: "mast",
  hostname: "localhost",
  port: 7544,
  database: "mast_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :mast, MastWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4005],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "1ekc54mrbwQbNh54La5WHx1P+FEOsPdSBpwSIUsKWFyxPeL2CcRfA+yaVcg1hSAP",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:mast, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:mast, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :mast, MastWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/mast_web/router\.ex$"E,
      ~r"lib/mast_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :mast, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
