import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :mast, MastWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# HTTPS is the responsibility of the reverse proxy in front of Mast, not the
# app itself. Operators terminating TLS at a proxy should add HSTS there and
# set `MAST_HTTPS=true` so generated URLs use the https scheme.

# Do not print debug messages in production
config :logger, level: :info

# JSON-formatted logs for production. Dev/test keep the default text logger
# so terminal output stays readable. See issue #2.
config :logger, :default_handler,
  formatter:
    {LoggerJSON.Formatters.Basic,
     metadata: [:request_id, :server_id, :private_key_id, :run_id, :job_id]}

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
